import type { Metadata } from "next";
import { Poppins, Inter, Cairo, Tajawal } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: "400",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "400",
});
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
  weight: "400",
});
const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden ${poppinsSans.variable} ${inter.variable} ${cairo.variable} ${tajawal.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
